[package]
name = "adnix-rs"
version = "0.1.0"
authors = ["Harsh Shandilya <msfjarvis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.1.18"
clap = "2.33.0"
